server:
  port: ${SERVER_PORT}

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      database: ${SPRING_DATA_REDIS_DATABASE}
  application:
    name: catalog-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8080/realms/comparo/protocol/openid-connect/certs}
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}