server:
  port: ${SERVER_PORT:8009}

spring:
  application:
    name: review-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/comparo_reviews}
    username: ${SPRING_DATASOURCE_USERNAME:comparo_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:secure_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add.type.headers: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8080/realms/comparo/protocol/openid-connect/certs}

app:
  kafka:
    topics:
      product-ratings: ${APP_KAFKA_TOPICS_PRODUCT_RATINGS:product-ratings}